### ISSUE TITLE
failed to import "from odc.dscache.tools.tiling import parse_group_name"

### ISSUE THREAD

**Issue by fivejjs** [opendatacube/odc-tools#146]
I run the import in sandbox default environment. It could be the version issue. 
```python
from odc.dscache.tools.tiling import parse_group_name
```

errors
```
ImportError: cannot import name 'parse_group_name'
```

**Comment by Kirill888** [comment]
those things have been moved around a lot, what are you running?

**Comment by Kirill888** [comment]
https://github.com/opendatacube/odc-tools/blob/4c017f6bb846e950d6889c476ae840bd223f541a/libs/dscache/tests/test_dscache.py#L1-L9

**Comment by fivejjs** [comment]
sandbox default python environment
