### ISSUE TITLE
stac-to-dc: index_update_datasets not found

### ISSUE THREAD

**Issue by 16EAGLE** [opendatacube/odc-tools#230]
Hi, thanks everyone for this great initiative. 

Just a quick bug report of an error that emerged since the most recent changes to https://github.com/opendatacube/odc-tools/blob/develop/apps/dc_tools/odc/apps/dc_tools/stac_api_to_dc.py. After installing from https://packages.dea.ga.gov.au using

```
pip3 install --extra-index-url="https://packages.dea.ga.gov.au" odc-apps-dc-tools
```
and running `stac-to-dc`, e.g. as is without arguments or with
```
stac-to-dc --bbox='25,20,35,30' --collections='sentinel-s2-l2a-cogs' --datetime='2020-01-01/2020-03-31' s2_l2a
```
the function `index_update_datasets` which previously was defined in that file is not found and I encounter:
```
Traceback (most recent call last):
  File "/home/UNI-WUERZBURG.EU/jas24nx/.local/bin/stac-to-dc", line 5, in <module>
    from odc.apps.dc_tools.stac_api_to_dc import cli
  File "/home/UNI-WUERZBURG.EU/jas24nx/.local/lib/python3.8/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 15, in <module>
    from odc.apps.dc_tools.utils import index_update_datasets
ImportError: cannot import name 'index_update_datasets' from 'odc.apps.dc_tools.utils' (/home/UNI-WUERZBURG.EU/jas24nx/.local/lib/python3.8/site-packages/odc/apps/dc_tools/utils.py)
```
When installing another recent version, e.g. `0.1.dev1024+g921bd72` with
```
pip3 install --extra-index-url="https://packages.dea.ga.gov.au" odc-apps-dc-tools==0.1.dev1024+g921bd72
```
and running the example above, everything works as expected.

It is unclear to me from where `index_update_datasets` is exported in the most recent version (I only see `index_update_dataset` without the "s" in `odc.apps.dc_tools.utils`) which is why I reverted to a previous version.

**Comment by alexgleith** [comment]
Sorry, I messed up some things a bit. SHould be fixed now!

**Comment by 16EAGLE** [comment]
Thanks!
