### ISSUE TITLE
There's no integration tests

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/odc-tools#244]
Some of the tools in this repository rely on the ODC Database to do their work.

We do mock things like SQS or datasets and run simple functional tests, but some tools like `sqs-to-dc` or `s3-to-dc` really need to be tested end-to-end.

Can we have a discussion about how to set up some integration tests?

The simplest way is to have a shell script that calls the tools, with a Docker Compose file that sets up an environment.

More complex is having an environment that can be bootstapped and then mocking things like SQS and S3 to do the testing from.

Thoughts?

**Comment by kieranricardo** [comment]
@alexgleith the bulk of the work seems to happen in functions like `queue_to_odc` which accept a `Datacube` and only really use a few functions from it. We could go a long way towards fully testing by mocking a `Datacube` and using this in our tests.

Although I agree that full testing would be ideal! but this might be a lot easier

**Comment by alexgleith** [comment]
Hey @jeremyh do you think it's plausible at all to mock a Datacube instance? It'll be a crazy amount or work, right...

**Comment by kieranricardo** [comment]
not all of it though! afaik we only need:

- ` dc.index.datasets.has`
- `dc.index.products.get_by_name`
- `dc.index.datasets.bulk_get`
- `dc.index.datasets.add` (can do nothing in mocked dc)
- `dc.index.datasets.update` (can do nothing in mocked dc)
- `dc.index.datasets.archive` (can do nothing in mocked dc)

**Comment by kieranricardo** [comment]
I've also done some work in stats creating test datasets products that we can leverage https://github.com/opendatacube/odc-tools/blob/fbf58611b52bb935fed52ab504214235490decb6/libs/stats/tests/test_utils.py#L192

**Comment by jeremyh** [comment]
Yeah, you could just mock those methods you use. I think the majority of bugs we hit deal with quirks in the interaction of a real ODC instances, though. Especially across different version of ODC and postgres etc.


One option is to use the pytest plugin for ODC in the digitalearthau repository -- it's what Explorer and others use.

To try it, add the plugin to your pytest `conftest.py`:
```
pytest_plugins = "digitalearthau.testing.plugin"
```

Now there are pytest fixtures available called `index` and `dea_index` (the latter includes DEA's products already added to the db). 

```
# Use in a test:
def test_with_datacube(index: Index):
    index.datasets.add(...)
    dc = Datacube(index)
    ... etc

# Or create your own fixture with preloaded data
@pytest.fixture
def my_index(index: Index):
    # Add data.
    return index

def test_with_my_index(my_index: Index):
    ....
```

The DB schema is reset individually for each test that's run (by default).

(by default, it will connect to database `dea_integration` on localhost. But you can add a `~/.datacube_integration.conf` with custom config, identical to a standard `~/.datacube.conf`... and you'd need docker compose or similar, as with Explorer, for doing this in Github Actions)

**Comment by whatnick** [comment]
I will backport tests from `datacube-docker` and add the [docker-compose](https://github.com/opendatacube/datacube-docker/blob/main/index/docker-compose.yml) stack to test this in a way I am familiar with.
