### ISSUE TITLE
We need a tool that indexes from a file system

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/odc-tools#253]
* s3-to-dc works really well from S3
* sqs-to-dc works great from a queue
* datacube dataset add works great for many places
* But we don't have one of these `fs-to-dc` that is fast and convenient...

Alternative is adding STAC indexing to the datacube-core codebase...

**Comment by omad** [comment]
Someone has added one!

https://github.com/opendatacube/odc-tools/blob/develop/apps/dc_tools/odc/apps/dc_tools/fs_to_dc.py

**Comment by alexgleith** [comment]
It was me, yay!
