### ISSUE TITLE
Feature: add indexing of Copernicus global DEM

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/odc-tools#264]
Source and metadata: https://registry.opendata.aws/copernicus-dem/

Take inspiration from the ESRI Land Cover to DC tool: https://github.com/opendatacube/odc-tools/blob/develop/apps/dc_tools/odc/apps/dc_tools/esri_land_cover_to_dc.py

**Comment by omad** [comment]
Implemented in October 2021. See https://github.com/opendatacube/odc-tools/blob/develop/apps/dc_tools/odc/apps/dc_tools/cop_dem_to_dc.py
