### ISSUE TITLE
Replace sat-search with pystac-client

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/odc-tools#274]
See: https://github.com/stac-utils/pystac-client

stac_api_to_dc.py needs it.

**Comment by Kirill888** [comment]
`pystac-client` demands `pystac==0.5.6`, which now uses different name for projection extension. `pystac` is now used by `odc.stats.model` but dependency on specific version of `pystac` has not been declared for this lib and it looks like code in `odc.stats.model.` expects older version of `pystac` than what `pystac-client` needs.

**Comment by alexgleith** [comment]
I think I fixed that, @Kirill888.

**Comment by Kirill888** [comment]
So does this only work with pystac>1 and unreleased pystac client?

https://github.com/opendatacube/odc-tools/blob/7f3790cd6c01d21b06a45d39aef6e4185f270057/docker/requirements.txt#L36

fails here for me:
https://github.com/opendatacube/odc-tools/blob/7f3790cd6c01d21b06a45d39aef6e4185f270057/libs/stats/odc/stats/model.py#L18

if this requires `pystac>=1` `odc/stats/setup.py` should be updated, and maybe some other

**Comment by Kirill888** [comment]
I think this is done now
