### ISSUE TITLE
Specify region?

### ISSUE THREAD

**Issue by patfla** [opendatacube/odc-tools#296]
From the Open Data Cube project I'm trying, and failing, to run the following:

> (cubeenv) D:\xyz\miniconda3\envs\cubeenv\Scripts>s3-to-dc --no-sign-request 's3://dea-public-data/geomedian-australia/v2.1.0/L8/**/*.yaml' ls8_nbart_geomedian_annual
> D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\datacube\drivers\postgres\_connections.py:81: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
>   EngineUrl(
> Traceback (most recent call last):
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\Pat\miniconda3\envs\cubeenv\Scripts\s3-to-dc.exe\__main__.py", line 7, in <module>
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\apps\dc_tools\s3_to_dc.py", line 129, in cli
>     added, failed = dump_to_odc(
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\apps\dc_tools\s3_to_dc.py", line 56, in dump_to_odc
>     for uri, metadata in uris_docs:
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\index\_index.py", line 59, in parse_doc_stream
>     for uri, doc in doc_stream:
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\apps\dc_tools\s3_to_dc.py", line 31, in stream_docs
>     for document in documents:
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\aio\__init__.py", line 494, in __call__
>     for rr, ee in future_results(
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\ppt\__init__.py", line 85, in future_results
>     have_more = fill(it, need_n, active)
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\ppt\__init__.py", line 70, in fill
>     x = next(src)
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\aio\__init__.py", line 486, in generate_requests
>     for url in urls:
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\apps\dc_tools\s3_to_dc.py", line 25, in stream_urls
>     for url in urls:
>   File "D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\aio\__init__.py", line 432, in find
>     raise IOError(f"Failed to list: {url}")
> OSError: Failed to list: 's3://dea-public-data/geomedian-australia/v2.1.0/L8/

Overwrote D:\Pat\miniconda3\envs\cubeenv\lib\site-packages\odc\aio\__init__.py as follows:

> def auto_find_region(
>     session: Optional[Session] = None, default: Optional[str] = 'ap-southeast-2'
> ) -> str:
>     """
>     Try to figure out which region name to use

Didn't help.

**Comment by patfla** [comment]
I've drilled down into this more.  In aio/__init__.py it exits in the finally here:

>         q = asyncio.Queue(1000, loop=self._async.loop)
>         ff = self._async.submit(find_to_queue, url, self._s3, q, **kw)
>         clean_exit = False
>         raise_error = False
> 
>         try:
>             yield from self._async.from_queue(q)
>             raise_error = not ff.result()
>             clean_exit = True
>         finally:
>             if not clean_exit:
>                 ff.cancel()
>             if raise_error:
>                 raise IOError(f"Failed to list: {url}")

That is, the async operation failed.  Within the context of globbing for *.yaml files.  As in:

s3-to-dc --no-sign-request 's3://dea-public-data/geomedian-australia/v2.1.0/L8/**/*.yaml' ls8_nbart_geomedian_annual

Why?

**Comment by Kirill888** [comment]
I have a feeling that on Windows command line character `'` doesn't get stripped away and is passed on to Python code which then causes failures much later than it should.

Don't have access to windows machine to verify though.

@alexgleith it's probably worth updating docs with Windows friendly version of that command.

**Comment by Kirill888** [comment]
@patfla error I get on Linux when injecting an extra `'` character is very similar to the one you reported, so I guess that's the reason for the failure, replace `'` with `"` and it should work?

Obviously datacube code should be more robust and detect an invalid URL on input in that case, but it does not currently.

**Comment by alexgleith** [comment]
Hmm, single quote vs double quote hey?

I just find that if I don't use quotes, on Mac OS, it fails because `zsh` tries to auto-fill the `*`s.

**Comment by Kirill888** [comment]
I thought that was the reason, we should probably have two versions of that command for `*nix` and `windows` users.

**Comment by patfla** [comment]
> 
> 
> @patfla error I get on Linux when injecting an extra `'` character is very similar to the one you reported, so I guess that's the reason for the failure, replace `'` with `"` and it should work?
> 
> Obviously datacube code should be more robust and detect an invalid URL on input in that case, but it does not currently.

@Kirill888  Thanks - double-quotes worked:

> (cubeenv) d:\xyz\miniconda3\envs\cubeenv\Scripts>s3-to-dc --no-sign-request "s3://dea-public-data/geomedian-australia/v2.1.0/L8/**/*.yaml" ls8_nbart_geomedian_annual
> Added 10427 datasets and failed 0 datasets.
