### ISSUE TITLE
Task: establish release process for publishing to PyPI

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#309]
Current State
==========

On every PR merge to `develop` branch all sub-modules are rebuilt with automatically generated `dev` version number and then uploaded to `https://packages.dea.ga.gov.au/` (via a push to S3 bucket under Digital Earth Australia AWS account).

This allows installation via `pip install` so long as `--extra-index-url="https://packages.dea.ga.gov.au/"` option is supplied. This works fine and we intend to keep pushing to `packages.dea.` for every merge to `develop` branch. But there are some issues with this as well:

- Version changes for every package even if no code was changed in that particular module
- Extra steps for installation since it's not on pypi
- Potential security concern if someone uploads malicious versions of `odc-` packages to PyPI

Publishing to PyPI
==============

There are no major blockers to this. But there are some issues to iron out for automating this process. Main issue is that we have multiple packages under one git repository, as a result there is no obvious way to do release tagging.

There are several approached we can take:

1. Keep common versions across all libs. This simplifies release process at the expense of bumping versions of packages that have not really changed.
2. Don't use git tags and instead trigger release when `_version.py` for a given module changes, this would allow independent version management, but makes it harder to track from what point in git history was used to make a release.
3. Use per library tags. For example to release `odc.algo` with version `0.1.2`, edit `odc/algo/_version.py` and create tag named `algo-0.1.2`. We can then automate that with GitHub Actions workflow that can be manually triggered by an operator.

Immediate Actions
==============

I would like to manually push all the `odc.*` libs to PyPI with version `0.2.0a`, current latest version in `packages.dea.*` is `0.2.dev2249`. I will then change automatic version numbering for `dev` releases to be 

```
{major}.{minor}.{micro+1}-dev{BuildNumber}
```
so that `dev` releases take precedence over what's on PyPI, next dev version will then be:

```
0.2.1-dev{BuildNumber}
```

And version recorded in `odc/{lib}/_version.py` will match the last release to PyPI, so will contain `0.2.0a` in there.

**Comment by uchchwhash** [comment]
Option 1 looks pretty good to me!

**Comment by Kirill888** [comment]
fyi @gadomski

**Comment by gadomski** [comment]
From a semantic versioning perspective, option 1 could be problematic once (if?) **odc-tools** hits v1. If one package needs a breaking change, it wouldn't really be correct to increment the major version for _all_ **odc-tools** packages.

While we're in v0.* it doesn't really matter, and if we think we'll stay there indefinitely, then option 1 does seem like the easiest. If we want to future-proof against a potential v1 then my vote is for either option 3, or an option 4 where any v1 subpackages are moved to their own repository (we have some experience w/ this breakout process in **stactools**).

**Comment by Kirill888** [comment]
I feel like "publish only if module has changed" makes most sense and is not that hard to achieve with github actions. I'm thinking matrix build can do this, the only "tricky" part is parsing `git reflog` to check if there has been changes to a given directory. Getting a list of changed files is not a native operation in github actions but there are plenty of non-official actions that exist

This one looks like a most relevant one to me:

https://github.com/dorny/paths-filter

And since PyPI tokens can have either global or per-project scope, but not "several projects" scope, pushing each one individually would allow avoiding creating "global scope" token.
