### ISSUE TITLE
Proposal: Rename odc-index to odc-stac

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#330]
I would like to propose we rename `odc-index` to `odc-stac`  at a "pypi project" level and at git filesystem level. We will still keep `odc.index.*` import for various datacube specific tools we have in there, but we would also include `odc.stac.*`  namespace in that same package. So the impact will be at `setup.{cfg,py}`  level initially, it's important to get naming right early on, these things are much harder after releases are made and started being used.

Package `odc-index` started off as a bunch of "missing tooling" for `datacube` index operations. Then we added some STAC to ODC adapters and hoping to add more. From user perspective it makes more sense to `pip install odc-stac` than `pip install odc-index` for the task of "working with STAC data", which will be the most likely external user-facing activity.

**Comment by Kirill888** [comment]
ping: @alexgleith @gadomski

**Comment by alexgleith** [comment]
I'm fully on board with this.

👍 from me

**Comment by gadomski** [comment]
👍🏽
