### ISSUE TITLE
Convert the thumbnail generation to lazy execution

### ISSUE THREAD

**Issue by supermarkion** [opendatacube/odc-tools#347]
Based on the feedback from: https://github.com/opendatacube/odc-tools/pull/340. The thumbnail relative code is not lazy execution, will slow the performance, or meet SQS timeout.

Sai will fix it cause he introduce it.

**Comment by omad** [comment]
Can you confirm whether this is done yet Sai?

If so, please close this issue.

**Comment by supermarkion** [comment]
Based on the recently big scale performance test, there is no significant performance issue with thumbnail feature. So I would prefer remember this risk, but not do anything now.
