### ISSUE TITLE
Issues and improvements for `fs-to-dc`

### ISSUE THREAD

**Issue by omad** [opendatacube/odc-tools#367]
I'm interested in using `fs-to-dc`, but there's two improvements I want to make, but discuss first.

**Feature query/improvement**

I think it would make more sense to leave globbing and finding files up to the shell and other unix commands. Instead of doing it within python. I'd like to change the command to receive a list of paths to index, instead of an `input_directory` and `glob`. 

I think it would make the code simpler and the tool more flexible.

https://github.com/opendatacube/odc-tools/blob/836823d14f8071b6662be83211412824aa74d2a3/apps/dc_tools/odc/apps/dc_tools/fs_to_dc.py#L38-L42

**Bugfix**

JSON can be loaded as YAML, but not vice-versa, so I'll change this
https://github.com/opendatacube/odc-tools/blob/836823d14f8071b6662be83211412824aa74d2a3/apps/dc_tools/odc/apps/dc_tools/fs_to_dc.py#L55-L56

**Comment by RichardScottOZ** [comment]
If someone is not using it on unix, what happens?

**Comment by Kirill888** [comment]
Issue with external globing is that command line is finite and it's relatively easy to truncate it. Yes you can use xargs with the right set of flags to avoid that, but if you just do `fs-to-ds some-dir/**/*yaml` you are likely to miss some files without ever knowing.

**Comment by RichardScottOZ** [comment]
and is different on different systems

**Comment by omad** [comment]
On Linux, there isn't any other software I use from the command line than handles local file globbing internally. I find it frustratingly inflexible.

By deferring to other tools like `find` and `xargs` I can:
- Save the list of files I want to index into a separate file to check before running the indexing
- Generate the list from a database or source other than the filesystem
- Perform more powerful filtering based on file attributes other than filename, or more advanced filename filters than just a glob
- Run several instances in parallel using `xargs` without modifying the python code

I guess it depends whether we want something that's comfortable on Windows, where globbing *is* typically handled internally, or something that fits with the other datacube tools, which follow a more unix like philosophy.

**Comment by alexgleith** [comment]
This is intended to be a very simple tool.

What you want to do, @omad, can already be done using a combination of unix file listing and "dc-index-from-tar", which is definitely a more "chain the tools together" way.

I do definitely think that the bug should be fixed!

**Comment by Kirill888** [comment]
Accepting a list of files to process is fine, it's just passing it directly as individual paths on a command line like what `datacube dataset` cli does is problematic. Pass it via stdin or from file, accepting thousands of paths on a command line is not cool though

**Comment by alexgleith** [comment]
The bug has been fixed, and the remaining issue is already handled by using other tools together.
