### ISSUE TITLE
Proposal: force formatting with black as a condition for merging PRs

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#375]
I would like to add formatting with `black` as a prerequisite for code merges. Idea is to add `black --check libs/ apps/` test at the very start of the workflow so that actions will fail early if code is checked in without being properly formatted.

Right now about half of all files would be reformatted by `black` tool, that's easy enough to fix, although it might cause merge issues for branches with significant changes that are currently in progress.

We can add pre-commit hooks as well I guess.

Actions:
1. Reformat everything with `black` 
2. Add `black --check` job as an early quality check that disables all other tests if not passing
3. Document requirements for code contribution
4. Formalize those checks with a script one can run locally within docker or proper environment
5. `[Maybe]` formalize those requirement with pre-commit hooks

**Comment by jeremyh** [comment]
:thumbsup: We've had good experiences with these on other repos. The reduction in code churn after conversion is great.

There's also  [shed](https://github.com/Zac-HD/shed#shed) if you want to go _all-in_ on normalisation (it's a wrapper for black+isort+others with zero configuration)

I've found pre-commit does make it a lot easier, as it will ensure all developers always use the same version of black automatically (and it runs tools from private virtualenvs, so you're always using the correct tools+versions for the current branch) 

You can then run `pre-commit run -a` from CI to check all files using your pre-commit settings.  No duplication.

(... and if you ever want to add checks+fixers other than black, like [Explorer's large list](https://github.com/opendatacube/datacube-explorer/blob/develop/.pre-commit-config.yaml) of them, pre-commit makes them easy to add+remove in one place without updating any environments)

@whatnick also said he's using https://pre-commit.ci/, which is an alternative to doing all this through Github Actions (and can auto-format/fix PRs for you). It looks like a good option.

**Comment by Kirill888** [comment]
This is very informative, thanks @jeremyh, shed looks interesting and by a fellow  Ken Behren too

**Comment by omad** [comment]
I think this is a great idea. I've even started once or twice but haven't finished yet.

It sounds like there is general support whenever someone gets around to doing the work.

**Comment by Kirill888** [comment]
I don't mind doing it, but there were some fairly active branches with many changes at the time this was first created, those have been merged now. So the impact should be minimal if done now.

**Comment by emmaai** [comment]
`.pre-commit-cfg.yaml` is added to force formatting and linting, but it only does so to the files changed, as those need to be committed. I messed up a bit with the last PR as Kirill pointed out. IMHO, it's too time consuming to do all the files in one big PR for a single person and to guarantee no mistake is made unintentionally. Alternatively, the more acceptable solution is to have formatting pushed in the same PR but different commit from the real change.

**Comment by omad** [comment]
As of #536 this is pretty much done. With tweaks possible in the future if we want.

- All code is formatted with `black`
- [pre-commit.ci](https://pre-commit.ci) is setup to both check all `pre-commit` rules, and auto-commit formatting changes to PR.

pre-commit is most helpful when contributors have it installed locally too, making for a tight feedback loop on formatting and code linting errors.
