### ISSUE TITLE
Tweak release process to PyPi

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#381]
Currently code is only pushed to PyPi from `pypi/publish` branch. I have originally thought of using pull requests for this. But it's actually problematic as PRs on github do not support fast forward merges, so keeping `develop` and `pypi/publish` branches in sync via PRs is not possible. 

related: #299 

So instead I propose a different approach:

1. Make `pypi/publish` a protected branch to which only `opendatacube/admins` can push (Done)
2. Then publishing can be done from a developer machine like so

```bash
cd /tmp
git clone --branch pypi/publish git@github.com:opendatacube/odc-tools.git
git pull --ff-only origin develop
git push origin pypi/publish
```

**Comment by Kirill888** [comment]
ping: @alexgleith @NikitaGandhi

**Comment by alexgleith** [comment]
Sounds like an ok process. Let's ensure it's really prominent in the README, because if I don't do it for a while, I will forget.
