### ISSUE TITLE
Task: cleanup stale branches

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#402]
There are some branches that have not been pushed to in a while, they are quite behind the `develop` branch, yet contain a few commits, most likely those commits have been either integrated via some other branch or they were experiments that didn't succeed. These branches are mostly from `odc.stats` orchestration days.

![image](https://user-images.githubusercontent.com/1428024/135004955-61c1bb35-edad-48ca-ae4d-c63bb332c7b3.png)

@tebadi can you please have a look if there is anything in those branches that you wish to keep? If not please delete them.

@gadomski I assume it's safe to remove your branch? I think those fixes were incorporated already.

@kieranricardo yours isn't too stale, but I have a request for it as well: please create an issue describing problem you are fixing in that branch.

**Comment by tebadi** [comment]
I've deleted my three branches, they're no longer required.

**Comment by gadomski** [comment]
Yup same for my one.
