### ISSUE TITLE
Task: add feature to support remote YAML file as odc-stats run config path

### ISSUE THREAD

**Issue by supermarkion** [opendatacube/odc-tools#403]
Hello, @alexgleith, @omad and @Kirill888,

How are you.

I found the odc-stats run config [option](https://github.com/opendatacube/odc-tools/blob/develop/libs/stats/odc/stats/_cli_run.py#L49) only supports the dict content or local YAML file.

```
1) https://github.com/opendatacube/odc-tools/blob/develop/libs/stats/odc/stats/_cli_run.py#L49
2) https://github.com/opendatacube/odc-tools/blob/45542d24fcbfd8a9f3535ede57c435dff425a4bd/libs/stats/odc/stats/_cli_common.py#L89
3) https://github.com/opendatacube/odc-tools/blob/45542d24fcbfd8a9f3535ede57c435dff425a4bd/libs/io/odc/io/text.py#L38
4) https://github.com/opendatacube/odc-tools/blob/45542d24fcbfd8a9f3535ede57c435dff425a4bd/libs/io/odc/io/text.py#L42
```

I had these config saved as remote [YAML file](https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/services/odc-stats/geomedian/ga_ls8c_nbart_gm_cyear_3.yaml) in a Github repo. And I plan to change the code [here](https://github.com/opendatacube/odc-tools/blob/45542d24fcbfd8a9f3535ede57c435dff425a4bd/libs/io/odc/io/text.py#L43) to make it support the feature `loading config from Github raw file`. 

Consider I plan to change the shared methods, then I submit the plan here to start the discussion.

The relative PR will be linked soon.

Cheers

Sai

**Comment by Kirill888** [comment]
I don't think it's such a good idea, `odc.io` does not have a lot of dependencies right now, adding generic "slurp" file or any kind of url is not something I'd like to have in there. Besides this functionality is already available in `datacube` here

https://github.com/opendatacube/datacube-core/blob/d268f49d291cb42769f283b953ffb994c76ed4c5/datacube/utils/documents.py#L88

but we can't make `odc-io` depend on `datacube`. So I suggest you handle urls at the application level with datacube's `load_documents` function (write a simple wrapper around it as it produces a generator rather a single dict)

**Comment by supermarkion** [comment]
Thanks @Kirill888 , I am happy to handle it at application level. 

How about your team @alexgleith on solution `handle it at application level` ?

**Comment by alexgleith** [comment]
I don't mind.

**Comment by supermarkion** [comment]
No plan to crash all existing pipelines and lost backwards compatible. So no need this feature anymore.
