### ISSUE TITLE
Include eo3 auto-detection

### ISSUE THREAD

**Issue by whatnick** [opendatacube/odc-tools#41]
Move eo3 from CLI flag which is often missed by users to internal-heuristic which examines certain signature keys in YAML being indexed to auto-apply eo3 related post-processing.

Also retain current flag and issue deprecation warnings for backward compatibility.

**Comment by whatnick** [comment]
return 'grids' in doc and 'default' in doc['grids'] and 'transform' in doc['grids']['default']

**Comment by Kirill888** [comment]
no longer relevant, code moved to datacube core, and does include auto-detection
