### ISSUE TITLE
Task: extract odc-stac package into a separate repo

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#415]
## Introduction

I think it's time to start planning for extraction of `odc-stac` into a repository of it's own. `odc-tools` was initially meant for prototypes and other experiments, I feel like `odc-stac` is reaching certain level of maturity and independence from other parts of `odc-tools` to justify extraction to a repository of it's own.

Main issue I see is discussed in #355. Essentially previous implementation in `stac/transform.py` (`stac_transform`) that is targeting indexing rather than loading is duplicating a lot of functionality that has since been implemented in a more generic way in `stac/_eo3.py` (`stac2ds`). I feel like `stac_transform` is a little bit too "DEA specific" right now, as it's development has been primarily driven by indexing needs within Digital Earth Australia/Africa. Extracting `odc-stac` in it's current form into a separate repository will impact further tweaking DEA might need to do with that code.

## Option 1

Currently `stac_transform` is used by several applications in `odc.apps.dc_tools.` and also in `odc.stats.`. One option is to first move `transform.py` into `odc.apps.dc_tools` in it's current form, and delay any further refactoring of that code, this would then require making `odc.stats` depend on `odc.apps.dc_tools`, or apps within `odc.stats` that use `stac_transform` can be moved into `odc.apps.dc_tools`, I believe they are generic enough and don't need to be in stats anyway, the two stats apps are

- Collect a bunch of stac items into dataset cache
- Build mosaic from a bunch of stac items

Only relation to `odc-stats` is that those STAC Items are usually produced by `odc-stats`, there is no dependency on `odc.stats.*` library within those apps.

I think this is least disruptive to DEA, behaviour of indexing will remain the same and any further tweaking can continue to happen in `odc-tools` repository. 

## Option 2

Refactor `stac_transform` to use `stac2ds` internally, adding extra features as needed to `stac2ds` to support current behaviours of `stac_transform` (#355). Main risk with this approach is that output of `stac_transform` is likely to change from what it currently produces, UUID generation for example, product name, handling of STAC items that are not 1.0 spec compliant and who knows what else. Not sure what the operational impact of such change would be. After this refactoring `stac/transform.py` should shrink quite significantly and will mostly contain DEA/ODC specific configurations for known data sources so it would probably be better off moved into `odc/apps/` anyway.

## Summary

I feel like the best way forward is to go with _Option 1_: do least refactoring before extraction (just move `stac/transform.py` file and maybe move some apps from `odc.stats` to apps). Once this is done `odc-stac` can be moved to a separate repo.

**Comment by Kirill888** [comment]
@alexgleith @gadomski

**Comment by alexgleith** [comment]
I'm ok with option 1, it means explicit use of the new methods are required. This can then be done incrementally.

**Comment by Kirill888** [comment]
Moved to here:

https://github.com/opendatacube/odc-stac/

all packaging and docs have been updated with new urls
