### ISSUE TITLE
Record Statistician configuration into outputs

### ISSUE THREAD

**Issue by omad** [opendatacube/odc-tools#419]
**Summary**

Record enough information in outputs to be able to debug or reproduce them, without requiring access to the original configuration file.

**Details**

One of the original datacube design principles was the ability to trace the lineage of data, with enough detail to reproduce it if necessary.

At the moment statistician outputs are missing enough detail to be able to reproduce them, in particular, any configuration passed to the `StatsPlugin`. There may also be other configuration options which affect outputs, I'm not sure.

The predecessor of statistician ([datacube-stats](https://github.com/opendatacube/datacube-stats/)) supported reproducibility by
saving a full copy of it's configuration file into the output dataset yaml file.

I think a better approach for statistician is to save enough of the input configurations into the `.proc-info.yaml` file produced when using eo-datasets3 for writing metadata.

The combination of `input datasets + software versions + statistician` configuration should be sufficient to reproduce an output dataset.

I think it's important to record this information with the dataset, instead of relying on a potentially incorrect reference to a configuration file. It ensures there's no confusion about the configuration when initially reviewing outputs, and even more important, being able to review them further in the future.

**Comment by supermarkion** [comment]
Already finished the feature: dump `statistication configuration` information to proc-info.yaml in this [commit](https://github.com/opendatacube/odc-tools/commit/7a0413f49c28e82406a0a49f4ae6074b4d69c67e).

Right now, the `proc-info.yaml` has:
- statistician configuration information
- software versions (eodatasets3 version; ows version; odc-stats version; summary-plugin version)

The input datasets information (their relative UUID in `odc`) can be found from metadata files. If we need, I can also add them to `prodc-info.yaml`. E.g. their s3 uris in `proc-info.yaml`.

**Comment by omad** [comment]
Thank you Sai, that looks great.

I recall that the input products can come from CLI rather than the configuration file. Can you check that this information will be saved in `.proc-info.yaml` as well. It's another very important detail, that has been messed up in the past.

Saving the specific input dataset urls is an interesting idea. I can see some benefits, but I don't think it's strictly necessary, so lets not worry about it now.

**Comment by supermarkion** [comment]
For the `input products`: unfortunately, the `odc-stats run` does not have the input products information. The input products information are used in the `save-task` CLI.

However, we can also dump `*.db` information to `proc-info.yaml` (normally, it should be a S3 uri). The `*.db` (e.g. `ga_ls_wo_3_annual_2009.db`) can used to reference to the input products.

**Comment by Kirill888** [comment]
every dataset in dataset cache has a copy of the corresponding product attached to it, so product information is available at run-time `some_input_dataset.type`, of course "virtualized" datasets need to be handled specially, but the same applies to lineage tracking for products combining several input products.

You can also access all the products present in the dataset cache directly without getting a specific dataset out of it.
