### ISSUE TITLE
Support github https links for config yamls

### ISSUE THREAD

**Issue by cbur24** [opendatacube/odc-tools#431]
When running ODC-Statistician using the command `odc-stats run`, it is not currently possible to pass to the `config` or `plugin-config` parameters a https link to a .yaml stored on github  i.e. this isn't supported:

`odc-stats run --config=https://raw.githubusercontent.com/some_repo/config.yaml ...`

Suggesting an update to the [parse_yaml_file_or_inline](https://github.com/opendatacube/odc-tools/blob/23bf317e2798e793f228532ea6e31865fc533fde/libs/io/odc/io/text.py#L38) function to allow the user to provide a link to a config yaml stored on github or the like.

**Comment by alexgleith** [comment]
I think that this has been fixed by @supermarkion a week or so ago

**Comment by supermarkion** [comment]
Long story. We did not achieve the agreement on design at that moment. So close/cancel the relative [proposal](https://github.com/opendatacube/odc-tools/pull/404).

**Comment by cbur24** [comment]
ok thanks @supermarkion, The workaround is pretty simple so not a big deal
