### ISSUE TITLE
Proposal: ODC-tools split/clean-up

### ISSUE THREAD

**Issue by SpacemanPaul** [opendatacube/odc-tools#432]
odc-tools was conceived as a place for "ODC features that DEA is experimenting with or prototyping with the intention of being integrated into odc-core in the future."

However some parts of odc-tools have already grown into mission-critical tools, and the tangled experimental architectural anti-pattern of the tools repository makes it difficult for them to mature further.  Splitting odc-stac into a separate repository was an important step in the right direction.

Most pressingly for DEA, odc-stats (a.k.a. "statistician") is now a key part of DEA infrastructure and is being recommended to external users as the go-to tool for large scale batch processing in the cloud - it therefore strongly desirable to get odc-stats out of odc-tools and into a separate, cleaner repository.

### Guiding Principles

1. Get odc-stats out of odc-tools.
2. Ensure new odc-stats package has no dependencies on packages inside odc-tools repository.
3. Keep package inter-dependencies as clear and simple as possible.

#### 1.  odc-tools packages to be split into separate repos:

1. odc_cloud
2. odc_dscache
3. odc_algo
4. odc_stats

These packages appear to be fairly tightly focused and uncluttered: particularly odc_cloud and odc_dscache.

These libraries may include some experimental or specialised functions that are not used by odc-stats or other libraries - where practical, these should be moved to other new or existing experimental packages within odc-tools.

#### 2. Move all "algorithmic" code out of odc-stats into odc-algo.

Code specific to particular algorithms (e.g. geomad, fractional cover, wofs, etc.) are currently split between odc-algo and odc-stats.)  Ideally this should be consolidated into odc-algo, leaving odc-stats as containing only the core statistician library, with modules imported from odc-algo.

#### 3. Remove apps/libs split.

Most of the apps in odc-cloud-apps could be more usefully packaged with odc-cloud.

Similarly most of the apps in odc-apps-dc-tools could be more usefully packaged with either odc-stats, odc-cloud, or odc-stac.

Again, some experimental or highly specialised apps in these packages are probably best left inside odc-tools.

#### 4. Move statistician docker build into odc-stats

Currently releasing a new version of Statistician requires coordinated changes to the odc-stats and datacube-docker repos.  Docker builds of packages should live with the package, not in a separate docker repo.

#### 5. Libraries to stay in odc-tools

There seems no pressing reason to move odc-ui out of odc-tools.

odc-io is more complicated.  Some other packages currently depend on it to some degree, but it is too eclectic in its current form to be a candidate for extracting whole from odc-tools.  I think odc_io will most likely end up being split up, with functions moving to the packages that make the most use of them, with some functions being good candidates for merging into datacube-core.

#### 6. Longer term plans

After being moved to self-contained repositories,  longer term plans for ODC can come into play.  Some packages may end up being partially or totally merged into core, some packages will remain as separate packages - that either depend on, are depended on by core.

### Working with the Community

Simply movingpackages to new repositories should be largely invisible to users.

Moving functions/apps/source files between packages is more likely to break people's code and will require careful consultation and coordination to minimise impact.

Comments on all of the above are sought.

**Comment by alexgleith** [comment]
It's been suggested that many of the odc_apps applications should live in Datacube Core, which may or may not be a good idea. Some, like the general purpose indexing from S3 or SQS certainly could/should.

I do worry a bit about the interdependence of libs and apps and having them in separate repos is not necessarily simpler.

**Comment by Kirill888** [comment]
That sounds fine to me so long as history is fully preserved. I have used `git-filter-repo` to extract `odc-stac` and it worked fairly well. Code have moved around a bit so you'll need to include some older paths when extracting, but it's all very straightforward really.

Regarding your point 3.

Apps from `odc-apps-cloud` should be moved into `odc-cloud`, that I agree with. `odc-apps-dc-tools` is not as clear cut. It certainly does not fit with `odc-stac` as those things are way too DEA specific, they do not fit with `odc-stats` either. It's really indexing infrastructure tools that are mostly useful to DEA operators. You can take them out into separate repo or keep them here, I have no opinion on that.

Regarding `odc.io`, it's mostly just this that is being used by other libs:

https://github.com/opendatacube/odc-tools/blob/213e0db8ca265fb54fb75b553925e123ed412246/libs/io/odc/io/text.py#L159-L167

this is clearly the case where some code duplication is better than extra dependency. I have already removed `odc-stac->odc-io` dependency, it should be trivial to remove `odc-dscache->odc-io` dependency as well. `odc-stats` is using more parts from it, but same story: better off just interning those methods.

I'd suggest to first remove `odc-io` dependencies from packages that use it, and only then perform repository split.
