### ISSUE TITLE
ModuleNotFoundError: No module named 'odc'

### ISSUE THREAD

**Issue by jaunvl-github** [opendatacube/odc-tools#438]
Hi All,

Please I need some help.

Is there any step by step material to solve the following error.

ModuleNotFoundError: No module named 'odc'

Also all the resources and material on platforms are very helpful but I cant find any material on how to setup your computer so that the code works. That is making sure all the libraries are installed, environments are setup etc. Am I missing this.

Thanks

**Comment by Kirill888** [comment]
@jaunvl-github Python environment management is a tricky topic. I suggest you use `conda` to setup python environment that works for you. 

Sample environment is documented here:

https://github.com/opendatacube/odc-tools#for-conda-users
