### ISSUE TITLE
Split ODC-Stats into a separate repository

### ISSUE THREAD

**Issue by SpacemanPaul** [opendatacube/odc-tools#452]
General plan:

```
1. Preparation 
   a. Github:
      i. Create new (empty) datacube/odc_stats github repo.
      ii. Configure permissions, etc.
      iii. Add github secrets to repo
   b. My local machine (new repo):
      i. Locally create new clone odc-tools and do git filter-branch magic to the new clone to isolate stats files and git history.
      ii. Copy across github actions across from old odc-tools and edit it to be for separate stats repository.
      iii. Update version numbering system.
      iv. Copy across .gitignore, SECURITY.md, etc.
      v. Point remote at new repo.
   c. My local machine (old repo):
      i. Strip out libs/stats
      ii. Remove stats from github actions
      iii. Update README, etc.
2. PRs.
   a. Push and create PRs for odc_tools and odc_stats.
   b. Review, tweak, and approve both PRs.
   c. Merge PR in new odc-stats repo.
   d. Trigger/test Stats release.
   e. Merge PR in odc-tools repo.
3. Update odc-stats version number in docker statistician build.
```

N.B. The statistician docker image will be moved into the new odcs-stats repo after this.

Comments and discussion welcome.

**Comment by Kirill888** [comment]
@SpacemanPaul I recommend `git-filter-repo` 

https://github.com/newren/git-filter-repo

`filter-branch` is the old and hard way, I would also swap a and b steps.

**Comment by Kirill888** [comment]
I'll do the same for dscache, but first I'll remove odc.io dependency from that

**Comment by SpacemanPaul** [comment]
Re: git-filter-repo vs filter-branch: oh cool, thanks.  Speed isn't an issue (I've done a few test runs with filter-branch in clean clones and they've been pretty painless), but looks like filter-repo is a bit cleaner at least.

Re: dscache  yes, agreed.  I'm tempted to do the same for cloud and algo - then all stats is completely independent of tools.

**Comment by Kirill888** [comment]
I would prioritize moving `odc.index.*` into datacube proper over cloud/algo.

Code in here really should be in datacube
https://github.com/opendatacube/odc-stac/tree/develop/odc/index

also this makes `odc-dscache` depend on `odc-stac`, when it really does nothing with STAC and just uses utilities from `odc.index`.

**Comment by SpacemanPaul** [comment]
Stats split is pretty much ready go.  Just getting my head around the github actions.   @kirill888 - your split-out of `dscache` helped a lot.  Should be done by Monday 5th.

**Comment by SpacemanPaul** [comment]
And done.
