### ISSUE TITLE
Send SNS Notification after Successful Indexing with sqs-to-dc

### ISSUE THREAD

**Issue by omad** [opendatacube/odc-tools#495]
As part of the operations in Digital Earth Australia, we use `sqs-to-dc` to subscribe to notifications that new datasets are available on S3, and then add them to an ODC Index.

We also have [datacube-alchemist](https://github.com/opendatacube/datacube-alchemist/) subscribed to the same SQS to produce derivative data. We have regular failures due to a [race condition](https://en.wikipedia.org/wiki/Race_condition) whereby `datacube-alchemist` fails on it's first execution, because a new dataset hasn't been added to the ODC Index yet.

To solve this, I propose adding a new `--notify-sns <sns:arn>` flag to `sqs-to-dc`. When provided, a notification will be sent when each dataset is indexed into ODC.

This could potentially be useful for `s3-to-dc` as well, and should be quite easy to implement.

**Comment by omad** [comment]
Implemented by @Ariana-B in https://github.com/opendatacube/odc-tools/pull/519

**Comment by jmettes** [comment]
Similar: https://github.com/opendatacube/odc-tools/issues/516
