### ISSUE TITLE
Publish index actions to SNS topic

### ISSUE THREAD

**Issue by jmettes** [opendatacube/odc-tools#516]
With the introduction of the [`--archive-less-mature` maturity functionality](https://github.com/opendatacube/odc-tools/pull/507), now less mature (i.e., `NRT` and `interim`) datasets get archived on indexing of more mature datasets (i.e., `final`).

We have a need to also delete these datasets from S3, beyond just archiving them - as the NRT data can get quite large, and they're not needed anymore. It would be really handy if dc-tools were to publish `archive` actions to an SNS topic (i.e., the STAC document + message attribute: `{"status": "ARCHIVED", ...}`). This way, a job can handle tagging the relevant objects in S3 for deletion.

---

Additionally, this functionality might also be handy for indexing events. We have downstream derivative products (wofs and fc) that are processed on arrival of upstream ARD datasets. However, currently they run into race-conditions, because they are triggered for based on SNS events triggered by S3 bucket notifications, rather than by indexing events. So it might be more sensible to drive this downstream processing based on that actual availability of data in the datacube index (i.e., STAC document + message attribute: `{"status": "ADDED"}`, as opposed to their arrival on S3.

**Comment by SpacemanPaul** [comment]
I don't have a problem with this, as long as it doesn't put any extra overhead on users who don't want/need this functionality.  (i.e. would need to be optional and explicitly configured.)
