### ISSUE TITLE
Improve DsCache

### ISSUE THREAD

**Issue by whatnick** [opendatacube/odc-tools#53]
via @Kirill888  -> a pretty good "interchange format" , and also works for "fixed geometry" workflows.
needs more tooling: 
- Index from dscache
- Better query time selection (currently only supports whole product(s) creation)
- No good time index story yet, but probably feasible to add something
- Need to add lineage support

**Comment by Kirill888** [comment]
@uchchwhash before Slack looses it

### Better handling GridSpec/tiles

We need following methods on `DsCache`

1. `.add_grid(gs: GridSpec, name: str)`
2. `.add_grid_tiles(grid: str, tiles: Dict[Tuple[int, int], List[UUID]])`  this is currently done by `dstiler` should be moved into `DsCache`
3. `.grids() -> Dict[str, GridSpec]`
4. `.tiles(grid: str) -> List[Tuple[Tuple[int,int], int]]`  use `.groups()`  and filter with `.startswith(grid+"/")` then parse group name and return just the index tuple
5. `.stream_grid_tile(idx: Tuple[int,int], grid: str) -> Iterator[Dataset]`  which will just build group_name and delegate to `.stream_group(group_name)`

For (1) use `.append_info_dict('grids/'...)`
in (4) returns list of tuples xy index, dataset_count, just like .groups  but name replaced with 2d index tuple
Should probably also have `idx: Tuple[int,int], grid: str -> List[UUID]` function, delegates to `.get_group(..)`

**Comment by uchchwhash** [comment]
@whatnick I did what I could. Should we close this now?
