### ISSUE TITLE
s3-to-dc fails due to lineage

### ISSUE THREAD

**Issue by GeoFelpave** [opendatacube/odc-tools#560]
When using:

`s3-to-dc --stac 's3://bucket-name/folder-name/**/*.json ' 'produc_name'`

The indexing process gives the error below

```
odc.apps.dc_tools.utils.IndexingException: Failed to create dataset with error Error loading lineage dataset: Dataset metadata did not match product signature.
Dataset definition:
 {}
Product signature:
 {
    "product": {
        "name": "rainfall_chirps_daily"
    }
}, 
```

The --help is showing that Default is not to skip lineage, so is expected to be empty, so no lineage to match. The expected behaviour is not taken place.

The work around is to use the flag --skip-lineage.

Thanks

**Comment by Ariana-B** [comment]
Hi @GeoFelpave,
This error message is perhaps a little misleading. `Dataset definition: {}` does not mean that the dataset lineage is empty, only that there was no overlap between its contents and the product signature. Are you able to double check and see if the files in your s3 bucket indeed have `lineage: {}`?

**Comment by GeoFelpave** [comment]
This has now been solved under the latest version. As per @Ariana-B the lineage was checked and the dataset did not have lineage, the default behaviour of dc should be not to check per lineage as per documentation, which has been corrected
