### ISSUE TITLE
Avoid using `np.bool` in `to_rgb_np`

### ISSUE THREAD

**Issue by TomAugspurger** [opendatacube/odc-tools#570]
https://github.com/opendatacube/odc-tools/blob/5e086527eb7f93ed484e76859a50f246007dd850/libs/algo/odc/algo/_rgba.py#L69 uses `np.bool`, which was deprecated in NumPy 1.20 in favor of https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations, and removed in 1.24.0 (https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations).

The updated way to use it is just `bool`.

**Comment by robbibt** [comment]
Hey @TomAugspurger, just an FYI that the `rgba` functionality is now available in `odc-geo` too, as a direct method which is pretty handy: https://odc-geo.readthedocs.io/en/latest/_api/odc.geo.xr.ODCExtensionDs.to_rgba.html#odc.geo.xr.ODCExtensionDs.to_rgba
```
import odc.geo.xr

ds.odc.to_rgba(bands=..., vmin=..., vmax=...)
```

**Comment by TomAugspurger** [comment]
Thanks for that tip! Using `.odc.to_rgba` worked just fine for me.

**Comment by benjimin** [comment]
Thanks @TomAugspurger and @Ariana-B !
