### ISSUE TITLE
Warnings relating to SQLAlchemy in s3-to-dc

### ISSUE THREAD

**Issue by benjimin** [opendatacube/odc-tools#582]
When using s3-to-dc (to index STAC datasets into the ODC) it emits noisy warnings such as:

_/usr/local/lib/python3.8/dist-packages/datacube/drivers/postgres/_api.py:48: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)_

Tested with `opendatacube/datacube-index:0.2.1` (latest, several months old).

Most likely need to bump dependency versions (especially datacube-core) and release new container image.

**Comment by omad** [comment]
This should be fixed with the new `opendatacube/datacube-index:0.3.0`


https://hub.docker.com/r/opendatacube/datacube-index


![image](https://github.com/opendatacube/datacube-docker/assets/108979/261fd2e0-8c66-4120-9711-a5b5e904632c)
