### ISSUE TITLE
ODC Tools Broken on Python 3.12 - broken urlpath dependency

### ISSUE THREAD

**Issue by omad** [opendatacube/odc-tools#588]
The [urlpath · PyPI](https://pypi.org/project/urlpath/) package is used in ODC for a bit of URL handling. However, the package hasn't been updated in a couple of years and is broken in Python 3.12.

See: 
![image](https://github.com/opendatacube/odc-tools/assets/108979/3968ace7-162d-4a9a-bc39-58e859a83dbe)

and https://github.com/brandonschabell/urlpath/issues/6

We should just drop the dependency, doing whatever trivial rewriting is necessary.

**Comment by EReaso** [comment]
Still having this issue on MacOS 15.4 with Python 3.12.3.
