### ISSUE TITLE
Better Geometry handling for STAC indexing

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-tools#63]
I thinks this function here:

https://github.com/opendatacube/odc-tools/blob/faf273a0d12740857fe1e25c86bdd69428efe4e9/libs/index/odc/index/stac.py#L80-L98

should detect self-crossing geometries and not use them. If `lon/lat` geometry is self crossing then we should either skip geometry altogether (this is allowed by `eo3`) or, if we must (maybe explorer assumes geometry presence), we should generate geometry from `shape, transform`.

@alexgleith

**Comment by alexgleith** [comment]
Are we sure the geometries are self-crossing? I'll find one of the geometries again and check it out...

**Comment by Kirill888** [comment]
if not, then we should check for lat/lon bounds being crazy large

**Comment by Kirill888** [comment]
I guess not all of them, but some are

```python
uu = [
"956d64fe-a273-56ca-b14e-74439b7a3c66",
"4ff1fe1b-dff2-527c-a04d-e890ec2dc102",
"6793fe6e-03b0-5647-83d4-b6680b6b67fe",
"5e1678ca-4c5e-5b8e-a7b5-bba63c5c7830",
"01026fac-1c42-5ed4-a8c0-5c24a0e36516" ,   
]

[(u, dc.index.datasets.get(u).extent.is_valid) for u in uu]
```

```
[('956d64fe-a273-56ca-b14e-74439b7a3c66', False),
 ('4ff1fe1b-dff2-527c-a04d-e890ec2dc102', False),
 ('6793fe6e-03b0-5647-83d4-b6680b6b67fe', True),
 ('5e1678ca-4c5e-5b8e-a7b5-bba63c5c7830', True),
 ('01026fac-1c42-5ed4-a8c0-5c24a0e36516', True)]
```

**Comment by alexgleith** [comment]
Yeah, got it

Found a bunch:

```
"52666160-fe67-580a-9357-d26de263033f"	"{"type": "Polygon", "coordinates": [[[209759.0000000011, 9190241.0], [177592.33034647745, 9199318.096200155], [178361.5753206862, 9199378.037367087], [99961.00000000006, 9217076.569561763], [107982.82373954175, 9215385.57703154], [131523.64947788796, 9210255.570453627], [154260.01567186136, 9205066.862453688], [155847.8529472046, 9204363.776038656], [99960.99999999342, 9190241.0], [209759.0000000011, 9190241.0]]]}"	false	"Self-intersection[155402.702431011 9204560.88646391]"
"466f6457-627c-5839-b6cc-a210f317a913"	"{"type": "Polygon", "coordinates": [[[699960.9999999994, 5490220.999999999], [763045.6773532599, 5490221.0], [768613.1075714797, 5510914.0072368765], [699960.9999999997, 5532594.011844299], [719638.9797448025, 5527099.162436723], [743981.3223670749, 5519580.177079155], [743884.1451611486, 5519071.865540934], [699960.9999999994, 5490220.999999999]]]}"	false	"Self-intersection[743525.770262528 5518836.46741597]"
"f5ab21da-d663-552b-b6cf-d5be8d67b3e3"	"{"type": "Polygon", "coordinates": [[[699960.9999999994, 5390200.999999999], [765675.1073295285, 5499999.000000001], [699961.0000000005, 5499999.000000002], [736005.6477666908, 5390201.000000001], [699960.9999999994, 5390200.999999999]]]}"	false	"Self-intersection[723238.032524186 5429093.28235688]"
"c6297341-5ae6-5d80-a5af-6976c1153d22"	"{"type": "Polygon", "coordinates": [[[255957.24611400254, 5490220.999999999], [260235.68021239102, 5511881.515912148], [199981.00000000116, 5526655.83674948], [210256.15024520503, 5524722.995507264], [234525.65576172032, 5519001.9703875575], [235047.49780119926, 5518865.760770472], [235107.52950182022, 5518339.482858953], [199980.99999999895, 5490221.000000001], [255957.24611400254, 5490220.999999999]]]}"	false	"Self-intersection[234823.891457282 5518112.43305908]"
"b7b3a92b-41d7-5fd0-9eda-6f3369191d97"	"{"type": "Polygon", "coordinates": [[[209758.99999999674, 8490221.0], [187410.24778621487, 8525180.936866963], [99961.00000000134, 8540697.276594158], [114878.90053093003, 8538384.793680854], [119679.5391731612, 8537630.347275319], [139131.16561172792, 8534260.758445363], [139768.50861463603, 8534129.186358918], [144821.29669670662, 8532960.745260412], [99960.99999999593, 8490221.0], [209758.99999999674, 8490221.0]]]}"	false	"Self-intersection[144623.852675174 8532772.63444071]"
```

**Comment by alexgleith** [comment]
Another approach would be attempting to fix the geometry.

Using ST_MakeValid() does fix it, but splits it into a multi-polygon. I really want to check the STAC and then Sinergise's then ESA's metadata to see if it's broken there too...

**Comment by alexgleith** [comment]
Ok, one scene, `S2B_MSIL2A_20200605T222759_N0214_R072_T01MAN_20200606T005246` or `52666160-fe67-580a-9357-d26de263033f`.

Our projected geometry:
```
{
    "type": "Polygon",
    "coordinates": [
        [
            [
                209759.0000000011,
                9190241
            ],
            [
                177592.33034647745,
                9199318.096200155
            ],
            [
                178361.5753206862,
                9199378.037367087
            ],
            [
                99961.00000000006,
                9217076.569561763
            ],
            [
                107982.82373954175,
                9215385.57703154
            ],
            [
                131523.64947788796,
                9210255.570453627
            ],
            [
                154260.01567186136,
                9205066.862453688
            ],
            [
                155847.8529472046,
                9204363.776038656
            ],
            [
                99960.99999999342,
                9190241
            ],
            [
                209759.0000000011,
                9190241
            ]
        ]
    ]
}
```

STAC metadata: `s3://sentinel-cogs/sentinel-s2-l2a-cogs/2020/S2B_1MAN_20200605_0_L2A/S2B_1MAN_20200605_0_L2A.json`

their unprojected geometry:
```
{
  "type": "Polygon",
  "coordinates": [
    [
      [
        -179.62870206943484,
        -7.318068402830097
      ],
      [
        -179.91925894616006,
        -7.234271856021084
      ],
      [
        -179.91229643920408,
        -7.233774914774684
      ],
      [
        179.37995190200598,
        -7.068910096538457
      ],
      [
        179.45233081051657,
        -7.084735432397175
      ],
      [
        179.66478195133757,
        -7.132638698878384
      ],
      [
        179.87004162590765,
        -7.18094491660202
      ],
      [
        179.88435839765512,
        -7.187393310123412
      ],
      [
        179.3780305289156,
        -7.311173932117743
      ],
      [
        -179.62870206943484,
        -7.318068402830097
      ]
    ]
  ]
}
```

Which is _valid_ but only if you handle longitude -179 as 181...

**Comment by alexgleith** [comment]
So really, it's just anti-meridian handling that is still broken. We can dodge this by not indexing these scenes at all. Or we somehow fix up our geometry transformations to handle these cases in the ODC.

**Comment by Kirill888** [comment]
Maybe it's anti-meridian or maybe it's just rounding errors of the  `native->lat,lon->native` conversion loop:

![image](https://user-images.githubusercontent.com/1428024/85496278-60a6b180-b61f-11ea-8c27-478c58e5fa43.png)

Either way, if projected geometry comes back as invalid we should not include it.

**Comment by Kirill888** [comment]
`aws s3 cp s3://sentinel-cogs/sentinel-s2-l2a-cogs/2020/S2A_1MAN_20200610_0_L2A/SCL.tif`

Looked at the image and it has lower bottom corner filled with data, but could only view it native projection in QGIS,
![image](https://user-images.githubusercontent.com/1428024/85498095-69e54d80-b622-11ea-8be7-1a7b0e798438.png)

map doesn't render in that projection, and when trying to swicth to espg:4326 I get this warning

```
An alternative, ballpark-only transform was used when transforming coordinates between EPSG:4322 - WGS 72 and EPSG:32701 - WGS 84 / UTM zone 1S. The results may not match those obtained by using the preferred operation:
Possibly an incorrect choice of operation was made for transformations between these reference systems. Check the Project Properties and ensure that the selected transform operations are applicable over the whole extent of the current project.
```

and qgis doesn't display anything.

**Comment by alexgleith** [comment]
If you're really careful, you can see them all in `4326`

![image](https://user-images.githubusercontent.com/3445853/85499194-7f5b7700-b624-11ea-95ab-3f227a1860bb.png)

Dark grey is the unprojected (but fixed lat/lon) coords, with the `-179` values changed to `191`. The projected coordinates are twisted because only some of the nodes end up on the other side of the world. The raster variously disappears, depending on how it's reprojected on the fly...

I guess I'm ok with skipping the invalid reprojected geometry, though creating valid geometry would be better.

If we're really keen to fix it properly, we can go back to the Sinergise metadata, which is in the original coordinates, funnily enough: https://roda.sentinel-hub.com/sentinel-s2-l2a/tiles/1/M/AN/2020/6/5/0/tileInfo.json.

**Comment by Kirill888** [comment]
@alexgleith for Matt
![image](https://user-images.githubusercontent.com/1428024/85506382-9a81b300-b633-11ea-8c71-ca72e80d852f.png)
