### ISSUE TITLE
odc.ui.mk_image_overlay fails if there is a 0-shape time axis

### ISSUE THREAD

**Issue by MatthewJA** [opendatacube/odc-tools#75]
Code to reproduce:

```python
import datacube
import odc.ui

dc = datacube.Datacube(app='repro')

ds = dc.load('s2a_ard_granule', y=(-32, -32.01), x=(153, 153.01), time='2018-01', output_crs='EPSG:3577', resolution=(-10, 10),
              measurements=['nbar_red', 'nbar_green', 'nbar_blue'], progress_cbk=odc.ui.with_ui_cbk())

odc.ui.mk_image_overlay(ds.isel(time=0))
```

Expected: I get an image overlay for the 0th time slice (in this case, the only time slice).
Actual: I get an IndexError on [line 165](https://github.com/opendatacube/odc-tools/blob/develop/libs/ui/odc/ui/_images.py#L165).

This works OK:

```python
odc.ui.mk_image_overlay(ds)
```

This does not:

```python
# This time there are multiple times in the data.
ds = dc.load('s2a_ard_granule', y=(-32, -32.01), x=(153, 153.01), time='2015', output_crs='EPSG:3577', resolution=(-10, 10),
              measurements=['nbar_red', 'nbar_green', 'nbar_blue'], progress_cbk=odc.ui.with_ui_cbk())

odc.ui.mk_image_overlay(ds)
```

This does not either:

```python
ds = dc.load('s2a_ard_granule', y=(-32, -32.01), x=(153, 153.01), time='2015', output_crs='EPSG:3577', resolution=(-10, 10),
              measurements=['nbar_red', 'nbar_green', 'nbar_blue'], progress_cbk=odc.ui.with_ui_cbk())

odc.ui.mk_image_overlay(ds.isel(time=0))
```

This works OK but is not intuitive:

```python
ds = dc.load('s2a_ard_granule', y=(-32, -32.01), x=(153, 153.01), time='2015', output_crs='EPSG:3577', resolution=(-10, 10),
              measurements=['nbar_red', 'nbar_green', 'nbar_blue'], progress_cbk=odc.ui.with_ui_cbk())

odc.ui.mk_image_overlay(ds.isel(time=[0])
```

**Comment by Kirill888** [comment]
yep it's a bug, code here

https://github.com/opendatacube/odc-tools/blob/2937876d91e2cdf417ed33177e1c3cedaf11d7a5/libs/ui/odc/ui/_images.py#L164-L173

Should only run if `time` *dimension* exists (and is not empty), this is different from `time` *coordinate*.

@MatthewJA by the way, `.mk_image_overlay(..)` expects inputs to be in the same projection as the map, which is usually `epsg:3857`, on-the fly reproject is not currently implemented, so you will need to load data appropriately.

**Comment by Kirill888** [comment]
fixed in `develop` branch.
