### ISSUE TITLE
aiohttp > v4 deprecates verify_ssl and impacts s3-to-dc

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/odc-tools#76]
Hi folks,

Just ran into a problem with s3-to-dc showing an error with verify_ssl not being a valid argument.
The aiohttp >4.0.0 release has removed the deprecated argument which has been replaced with some new ones.
From what I can figure aiobotocore is not yet compatible and isn't pinning for aiohttp<4.0.0. 
Pinning aiohttp<4.0.0 in my ci/cd resolved the issue for the moment.

My python is still pretty rough around the edges but I though it was worth noting here in case odc-tools build system hits the same issue and/or I am making a mistake in the analysis.
let the python gurus speak! :-)

**Comment by Kirill888** [comment]
I don't think we use `aiohttp` directly, only via `aiobotocore`. So it's probably the matter of bumping `aiobotocore` version, assuming they have a compatible version.

**Comment by woodcockr** [comment]
^yep, that's what I attempted to say. It's an aiobotocore issue, but its also ours whilst that is fixed so adding in aiohttp<4.0.0 in our setups can work for now.

**Comment by Kirill888** [comment]
Ok, I should read more before replying...

I looked in `aibotocore` and the latest release we are using in the sandbox is still latest on github and does not contain a pin for `aiohttp`. But also `aiohttp` current release is `3.6.2`, do you have a flag somewhere to install pre-release libs?

https://pypi.org/project/aiohttp/#history

**Comment by woodcockr** [comment]
I should just write more clearly ;-)

looking at aiobotocore 1.0.7 (tag) on github setup.py says - 'aiohttp>=3.3.1'.

We do have a flag for pre-release libs, since some of the libs we use from odc are pre-release development versions. Might be trickling down and picking up the aiohttp 4 pre-release.
I didn't think of that.

**Comment by Kirill888** [comment]
https://github.com/GeoscienceAustralia/dea-sandbox/blob/a1068ecabe790cff118a4fe84b861c41fa0bed12/docker/requirements-odc.txt#L3 this is what we do to force pre-release datacube to be picked up without enabling pre-release globally, but this needs editing with every new release I guess. Maybe there is special mechanism in pip to apply flags like that per specific lib, but I'm not sure how that would look like in `requirements.txt`

**Comment by Kirill888** [comment]
Summary: use of `--pre` flag meant for `datacube` lib, triggered installation of unreleased version of `aiohttp` and caused breakage, solution: don't use global `--pre` in `requirements.txt`.
